services:
  # Database for testing
  postgres-test:
    image: postgres:15
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER:-kvd_user}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD:-devpassword123}
      - POSTGRES_DB=${TEST_POSTGRES_DB:-kvd_test}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER:-kvd_user} -d ${TEST_POSTGRES_DB:-kvd_test}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kvd_test_network

  # Run tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
      - ./test-results:/app/test-results
    environment:
      - TEST_DATABASE_URL=postgresql+asyncpg://${TEST_POSTGRES_USER:-kvd_user}:${TEST_POSTGRES_PASSWORD:-devpassword123}@postgres-test:5432/${TEST_POSTGRES_DB:-kvd_test}
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - kvd_test_network
    command: bash -c "mkdir -p test-results && python -m pytest"

networks:
  kvd_test_network:
    driver: bridge